version: '2.1'

services:
  zoo-cloud:
    image: zookeeper:3.4.9
    hostname: zoo-cloud
    ports:
      - "2182:2182"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2182
        ZOO_SERVERS: server.1=zoo-cloud:2888:3888
    volumes:
      - ./zk-single-kafka-single-cloud/zoo-cloud/data:/data
      - ./zk-single-kafka-single-cloud/zoo-cloud/datalog:/datalog

  kafka-cloud:
    image: confluentinc/cp-kafka:5.4.1
    hostname: kafka-cloud
    ports:
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka-cloud:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:29092
      KAFKA_CREATE_TOPICS: "topic1:1:1,topic2:1:1,todd-sample-interval-test:1:1"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo-cloud:2182"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./zk-single-kafka-single-cloud/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo-cloud
